[package]
name = "sun"
version = "0.7.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sun_core = { path = "../sun_core" }
sun_lib = { path = "../sun_lib" }
colorized = "1.0.0"
