[package]
name = "sun_lib"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sun_core = { path = "../sun_core" }

[lib]
